<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../onetorch/GameWorld.cs" Link="GameWorld.cs" />
    <Compile Include="../onetorch/PlayerAnimation.cs" Link="PlayerAnimation.cs" />
    <Compile Include="../onetorch/PlayerPreferences.cs" Link="PlayerPreferences.cs" />
  </ItemGroup>
</Project>
